version: '20.10.22'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  web:
    build:
      context: ./myshop
      dockerfile: Dockerfile
    container_name: django_container
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      REDIS_URL: redis://redis:6379/0

  bot:
    build:
      context: ./telegram_bot
      dockerfile: Dockerfile
    container_name: telegram-bot
    depends_on:
      - web
    environment:
      REDIS_URL: redis://redis:6379/0

  db:
    image: postgres:13.0-alpine
    container_name: postgres_db2
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: